### model
model_name_or_path: saves/qwen2.5/ko-en/qwen-ko/

### method
stage: pt
do_train: true
finetuning_type: lora
lora_target: all
additional_target: embed_tokens, lm_head, norm

lora_alpha: 32
lora_dropout: 0.1
lora_rank: 16



template: qwen
dataset: ko_pt1,ko_pt2,ko_pt3,ko_pt4
cutoff_len: 1024
max_samples: 8000000
overwrite_cache: false
preprocessing_num_workers: 16

output_dir: saves/qwen2.5/ko-en/pt/
logging_steps: 500
save_steps: 500
save_total_limit: 2
plot_loss: true
overwrite_output_dir: true
#resume_from_checkpoint: true

per_device_train_batch_size: 12
gradient_accumulation_steps: 8
learning_rate: 2.0e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
max_grad_norm: 1.0



val_size: 0.1
per_device_eval_batch_size: 12
eval_strategy: steps
eval_steps: 2000

